inherit_from: .rubocop_todo.yml

require:
  - ./lib/rubocop/cop/graphql/authorize_mutation

Graphql/AuthorizeMutation:
  Enabled: true
  Include:
    - app/graphql/mutations/**/*.rb
    - ee/app/graphql/mutations/**/*.rb

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  SuggestExtensions: false
  Exclude:
    - vendor/**/*
    - node_modules/**/*

Style/Documentation:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Metrics/MethodLength:
  Max: 20
